# -*- coding: utf-8 -*-
"""Basic Chatbot Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3SCNvOP40-58mpiOkVmOw47auaoCbFc
"""

pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

# Download NLTK data files
nltk.download('punkt')

# Define patterns and responses
pairs = [
    [
        r"hi|hello|hey",
        ["Hello! How can I assist you today?", "Hi there! How can I help you?"]
    ],
    [
        r"my name is (.*)",
        ["Hello %1, how can I help you today?", "Hi %1, what can I do for you?"]
    ],
    [
        r"how are you",
        ["I'm doing well, thank you! How about you?", "I'm great! How can I assist you today?"]
    ],
    [
        r"what is your name",
        ["I am a chatbot created to assist you.", "I'm a chatbot here to help you."]
    ],
    [
        r"(.*) (thanks|thank you)",
        ["You're welcome!", "No problem! If you need anything else, just ask."]
    ],
    [
        r"(.*) (quit|exit|bye)",
        ["Goodbye! Have a great day!", "Bye! Feel free to come back if you have more questions."]
    ],
    [
        r"(.*)",
        ["Sorry, I didn't understand that. Can you please rephrase?", "I’m not sure I understand. Can you tell me more?"]
    ]
]

# Create a chatbot instance
chatbot = Chat(pairs, reflections)

# Start the conversation
print("Chatbot: Hi there! Type 'quit' to exit.")
while True:
    user_input = input("You: ").lower()
    if user_input in ['quit', 'exit', 'bye']:
        print("Chatbot: Goodbye!")
        break
    else:
        response = chatbot.respond(user_input)
        print(f"Chatbot: {response}")